Repository kku-computer-science/git-group-repository-group-5-sec-2, pull requests merged in 2025-02, with the labels that each got.

#24 fix bug in highlight setting page and add ux/ui in table list
  InitialProject/CS2564_46/Source Code/Project_2-master/.devcontainer/devcontainer.json
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/highlight_papers/1739261316.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/highlight_papers/1739261337.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/highlight_papers/1739261892.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/resources/views/highlight/index.blade.php
Labels: bug, enhancement

#25 fix README.md
  InitialProject/CS2564_46/Source Code/Project_2-master/app/Models/ResearchProject.php
  InitialProject/CS2564_46/Source Code/Project_2-master/composer.json
  InitialProject/CS2564_46/Source Code/Project_2-master/docker-compose.yml
  README.md
Labels: documentation

#47 Redesign Tags checkbox
  InitialProject/CS2564_46/Source Code/Project_2-master/app/Http/Controllers/HighlightController.php
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/albumimg/1740250001_album16.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/albumimg/1740403493_1740242729_album1.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/albumimg/1740403493_1740242729_album2.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/albumimg/1740403493_1740242729_album3.jpeg
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/coverimg/1740403493_1740387414_1740249596_coverimg2.png
  InitialProject/CS2564_46/Source Code/Project_2-master/public/images/coverimg/1740405444_1740249779_coverimg5.png
  InitialProject/CS2564_46/Source Code/Project_2-master/resources/views/highlight/create.blade.php
  InitialProject/CS2564_46/Source Code/Project_2-master/resources/views/highlight/edit.blade.php
  InitialProject/CS2564_46/Source Code/Project_2-master/resources/views/highlight/index.blade.php
Labels: enhancement
